site_name: Documentation for test-mkdocs
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: .
nav:
  - Home: index.md
  - Project 1: program-py.md
  - Project 2: program-js.md
