site_name: Test Documentation
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: .
nav:
  - Home: docs/index.md
  - Project1:
    - program.py: project1/docs.md
  - Project2:
    - program.js: project2/docs.md
docs_dir: .
